// <auto-generated />
using System;
using Dextermd.ITDeveloper.Data.ORM;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dextermd.ITDeveloper.Data.Migrations
{
    [DbContext(typeof(ITDeveloperDbContext))]
    partial class ITDeveloperDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Dextermd.ITDeveloper.Domain.Entities.Mural", b =>
                {
                    b.Property<int>("MuralId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MuralId"), 1L, 1);

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Notification")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("MuralId");

                    b.ToTable("Mural");
                });

            modelBuilder.Entity("Dextermd.ITDeveloper.Domain.Models.Pacient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)")
                        .HasColumnName("Cpf")
                        .IsFixedLength();

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Email");

                    b.Property<DateTime>("HospitalizationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Name");

                    b.Property<Guid>("PacientStatusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Rg")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("Rg");

                    b.Property<DateTime>("RgIssueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RgOrgan")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("RgOrgan");

                    b.Property<int>("Sex")
                        .HasColumnType("int");

                    b.Property<int>("TypePacient")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PacientStatusId");

                    b.ToTable("Pacient", (string)null);
                });

            modelBuilder.Entity("Dextermd.ITDeveloper.Domain.Models.PacientStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Description");

                    b.HasKey("Id");

                    b.ToTable("PacientStatus", (string)null);
                });

            modelBuilder.Entity("Dextermd.ITDeveloper.Domain.Models.Pacient", b =>
                {
                    b.HasOne("Dextermd.ITDeveloper.Domain.Models.PacientStatus", "PacientStatus")
                        .WithMany("Pacient")
                        .HasForeignKey("PacientStatusId")
                        .IsRequired();

                    b.Navigation("PacientStatus");
                });

            modelBuilder.Entity("Dextermd.ITDeveloper.Domain.Models.PacientStatus", b =>
                {
                    b.Navigation("Pacient");
                });
#pragma warning restore 612, 618
        }
    }
}
